name: Build EXE with PyInstaller

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --noconsole main.py

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      run: |
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\": \"${{ steps.tag_version.outputs.new_tag }}\", \"name\": \"Release ${{ steps.tag_version.outputs.new_tag }}\"}" \
          https://api.github.com/repos/OWNER/REPO/releases)
        echo "Release response: $RESPONSE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Assuming main.exe is the output from PyInstaller
    - name: Upload Release Asset
      run: |
        RELEASE_ID=$(echo $RESPONSE | jq -r '.id')
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @./dist/ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe \
          "https://uploads.github.com/repos/OWNER/REPO/releases/$RELEASE_ID/assets?name=ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
