name: Build EXE with py2exe

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2exe

    - name: Create setup.py for py2exe
      run: |
        echo "from distutils.core import setup" > setup.py
        echo "import py2exe" >> setup.py
        echo "setup(console=['ShortenVideoTo140Sec.py'])" >> setup.py

    - name: Build EXE with py2exe
      run: python setup.py py2exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}

    - name: Upload EXE to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/ShortenVideoTo140Sec.exe
        asset_name: ShortenVideoTo140Sec.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}
