name: Build EXE with PyInstaller

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --noconsole main.py

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      run: |
        $response = curl -s -X POST `
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
          -H "Content-Type: application/json" `
          -d "{\"tag_name\": \"${{ steps.tag_version.outputs.new_tag }}\", \"name\": \"Release ${{ steps.tag_version.outputs.new_tag }}\"}" `
          https://api.github.com/repos/PiesP/ShortenVideoTo140Sec/releases
        echo "Release response: $response"
        $parsedResponse = $response | ConvertFrom-Json
        if ($parsedResponse -eq $null) {
          Write-Host "Failed to parse response or response is empty"
        }
        Write-Host "Parsed Response: $parsedResponse"
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      