name: Build EXE with cx_Freeze

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze

    - name: Create setup.py for cx_Freeze
      run: |
        echo "import sys" > setup.py
        echo "from cx_Freeze import setup, Executable" >> setup.py
        echo "setup(name='ShortenVideoTo140Sec'," >> setup.py
        echo "      version='0.1'," >> setup.py
        echo "      description='ShortenVideoTo140Sec'," >> setup.py
        echo "      executables=[Executable('ShortenVideoTo140Sec.py')])" >> setup.py

    - name: Build EXE with cx_Freeze
      run: python setup.py build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}

    - name: Upload EXE to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/exe.win-amd64-3.9/ShortenVideoTo140Sec.exe
        asset_name: ShortenVideoTo140Sec.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}
