name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install UPX
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "upx"
        echo "UPX_PATH=${{ github.workspace }}\upx\upx-3.96-win64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
  
    - name: Install project dependencies
      run: pip install -r requirements.txt
  
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --upx-dir $env:UPX_PATH ShortenVideoTo140Sec.py

    - name: Rename EXE for Release
      run: Rename-Item dist\ShortenVideoTo140Sec.exe ShortenVideoTo140Sec.exe
  
    - name: Generate tag from date
      run: echo "TAG=$(Get-Date -Format 'yyyyMMddHHmmss')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}

    - name: Upload EXE to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/ShortenVideoTo140Sec.exe
        asset_name: ShortenVideoTo140Sec.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}