name: Build EXE with Nuitka

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Nuitka and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka

    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest

    - name: Set Nuitka downloads environment variable
      run: echo "NUITKA_DOWNLOADS=1" >> $GITHUB_ENV

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Write version to file
      env:
        NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}
      run: |
        echo $NEW_TAG > version.txt

    - name: Update main.py with version
      run: |
        $version = Get-Content version.txt
        $mainPyPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "main.py"
        (Get-Content $mainPyPath) -replace 'VERSION_PLACEHOLDER', $version | Set-Content $mainPyPath
      shell: pwsh

    - name: Build EXE with Nuitka
      run: python -m nuitka --onefile --windows-disable-console main.py

    - name: Rename built EXE
      env:
        NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}
      run: |
        $newName = "ShortenVideoTo140Sec-$env:NEW_TAG.exe"
        $distPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "main.dist"
        $oldFilePath = Join-Path -Path $distPath -ChildPath "main.exe"
        $newFilePath = Join-Path -Path $distPath -ChildPath $newName
        Get-ChildItem $distPath | Write-Output
        if (Test-Path $oldFilePath) {
          Rename-Item -Path $oldFilePath -NewName $newFilePath
        } else {
          Write-Error "File $oldFilePath not found"
        }
      shell: pwsh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
