name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Read version from version.ini
      run: |
        $version = (Get-Content version.ini | Select-String 'ProductVersion=').ToString().Split('=')[1]
        echo "PRODUCT_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
  
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --noconsole main.py

    - name: Rename EXE for Release
      run: Rename-Item dist\main.exe "ShortenVideoTo140Sec-$($env:PRODUCT_VERSION).exe"
      
    - name: Generate tag from date
      run: |
        echo "TAG=$(Get-Date -Format 'yyyyMMddHHmmss')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/ShortenVideoTo140Sec-$env:PRODUCT_VERSION.exe
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_PAT }}
