name: Build EXE with PyInstaller

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --noconsole main.py

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
