name: Build EXE with PyInstaller

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --windowed --noconsole main.py

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      run: |
        $response = curl -s -X POST `
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
          -H "Content-Type: application/json" `
          -d "{\"tag_name\": \"${{ steps.tag_version.outputs.new_tag }}\", \"name\": \"Release ${{ steps.tag_version.outputs.new_tag }}\"}" `
          https://api.github.com/repos/PiesP/ShortenVideoTo140Sec/releases
        echo "Release response: $response"
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      run: |
        $releaseId = (ConvertFrom-Json $response).id
        $filePath = "${{ github.workspace }}/dist/ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe"
        curl -s -X POST `
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
          -H "Content-Type: application/octet-stream" `
          --data-binary @$filePath `
          "https://uploads.github.com/repos/PiesP/ShortenVideoTo140Sec/releases/$releaseId/assets?name=ShortenVideoTo140Sec-${{ steps.tag_version.outputs.new_tag }}.exe"
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

